### ISSUE TITLE
Black screen on webOS 4

### ISSUE THREAD

**Issue by gustavsgoldbergs** [mariotaku/ihsplay#11]
Same issue, but now the app just PANICKS and goes to live TV.

### IHSplay Information

Audio & video modules: ndl-webos4
IHSplay reported webOS version: 4.9.0
Settings reported webOS version: 4.9.7

### Computer Setup

Monitor: 1080p, 60hz
CPU	Intel(R) Core(TM) i3-2105 CPU @ 3.10GHz   3.10 GHz
RAM 4.00 GB
System type	64-bit operating system, x64-based processor

### P.S.

Re: #9 
This is a very cool concept, tbh. I would love this working.👍
Also, it looks like we don't have the same time zones.

**Comment by mariotaku** [comment]
Should be the same issue as #13. Also https://github.com/mariotaku/moonlight-tv/issues/110 and https://github.com/mariotaku/moonlight-tv/issues/184.

**Comment by mariotaku** [comment]
I think this has been fixed in 0.2.3. Feel free to reopen if it's not working, or create a new one for other issues.
