### ISSUE TITLE
[BUG]crash

### ISSUE THREAD

**Issue by feartr** [mariotaku/ihsplay#13]
hi dears
select computer ,start stream button click and connected. crashed closed ihsplay switch live tv.
[Yeni Metin Belgesi (2).txt](https://github.com/mariotaku/ihsplay/files/10530528/Yeni.Metin.Belgesi.2.txt)

**Comment by mariotaku** [comment]
Hi, I have started an investigation. Will let you know when I find something.

**Comment by feartr** [comment]
thank you. I cant wait for your solution

**Comment by mariotaku** [comment]
Hello, I made a snapshot for this issue. Could you try "webos-snapshot" in this link? https://github.com/mariotaku/ihsplay/actions/runs/4121566828

**Comment by feartr** [comment]
thank you working. Using the NetCast Legacy video decoder, and ndl audio
