### ISSUE TITLE
The video image is kind of restless

### ISSUE THREAD

**Issue by WADPH** [mariotaku/ihsplay#14]
hello, thank you for the project. Unfortunately, on my TV, your app is working strangely. It connects, there is sound and video. But the problem is that the video image is kind of restless. I really hope that you will help me. I'm sorry for my English, I don't speak it, so I have to use a translator

I think this may be due to the fact that it is necessary to change the bitrate, framerate and resolution settings. But there are items "option 1" "option 2" "option 3" and after I change 
 let's say the first one is on the second one and after I re-enter the settings, then everything will be as before. In short, the settings are not saved

Version: 0.2.2
Audio Module: lgnc
Video Module: lgnc
webOS Version: 3.9.0
__
![16756233366238993861983246625795](https://user-images.githubusercontent.com/75982625/216839103-54f72e82-e948-465e-9219-4b040a0278cc.jpg)

This is image after connecting pc to tv
![IMG_20230205_225834](https://user-images.githubusercontent.com/75982625/216839257-fde3bc43-ab3c-4b26-8da0-ff4ccdfb6d4f.jpg)

**Comment by mariotaku** [comment]
Hello, it seems that the video is not working properly. Do you have multiple monitors? Or it is a wide one? (like 21:9)

**Comment by WADPH** [comment]
> 

I have only one monitor and it is 16x9(1600x900 resolution)

**Comment by WADPH** [comment]
I have only one monitor and it is 16x9(1600x900 resolution)

**Comment by mariotaku** [comment]
Thank you. I'll investigate.

**Comment by WADPH** [comment]
> Привет, кажется, что видео не работает должным образом. У вас несколько мониторов? Или он широкий? (например, 21:9)

I have only one monitor and it is 16x9(1600x900 resolution)

**Comment by mariotaku** [comment]
Don't worry, I'll investigate and fix the issue. Although it may take some time.

**Comment by WADPH** [comment]
> Don't worry, I'll investigate and fix the issue. Although it may take some time.

thank you very much in advance if you find something let us know 
And I would also like to ask about the fact that why the settings do not change is this a bug or should it be?

**Comment by mariotaku** [comment]
It's a work in progress, and changes nothing, sorry.

**Comment by WADPH** [comment]
Hello, I also forgot to add (suddenly it will somehow help)

If anything, the image is not just "broken". If you allow to open a white background on a PC, then the broadcast on Tv will also be white. That is, the broadcast works, but it does not work correctly somehow. it's as if it's broken, and it needs to be put together like a puzzle

If you need, then I can post a video of exactly what I want to explain

Sorry for the clumsy English

**Comment by mariotaku** [comment]
Hello, I'm thinking if the 1600x900 resolution can be the reason. Could you try 1280x720?

**Comment by WADPH** [comment]
> Hello, I'm thinking if the 1600x900 resolution can be the reason. Could you try 1280x720?

Unfortunately that's not the point
I changed the resolution, but there is no result. These strange fragments just flash and change on the Tv screen, but this does not lead to a normal image
If anything, I changed the resolution both in the PC itself and in the settings of Remote Play (Steam)

**Comment by mariotaku** [comment]
Thanks for the info. I'll show some info of the video on the screen in future releases.

**Comment by WADPH** [comment]
> Thanks for the info. I'll show some info of the video on the screen in future releases.

Thank you too, I hope you will succeed
I can't wait for the moment when I can play games on my TV
Good luck to you!

**Comment by WADPH** [comment]
Oh my God, after the update everything works correctly. THANK YOU SO MUCH FOR THIS PROJECT
Good luck to you!

I think, you can close issue:)
Thanks again!

**Comment by mariotaku** [comment]
Very great to hear that. Happy gaming!
