### ISSUE TITLE
[BUG] No Sound on 55UM71007LB

### ISSUE THREAD

**Issue by Evil95** [mariotaku/ihsplay#18]
## Issue Summary

On my LG 55UM71007LB it work's great so far. The only issue is that i don't have any sound.

## Steps to Reproduce

1. Play something

## Expected Behavior

Working sound. :D

### IHSplay Information

LG 55UM71007LB
Version: 0.2.3
Audio Module: (null)
Video Module: ndl-webos4
webOS Version: 4.9.0

### Computer Setup
Windows 11
Gigabyte B450M S2H
AMD Ryzen 5 2600
AMD Radeon RX 5600 XT
Resolution: 1080p

**Comment by mariotaku** [comment]
Thanks for the report. It can be reproduced and will be fixed in v0.2.4.

**Comment by Evil95** [comment]
Thank you. I close this

**Comment by mariotaku** [comment]
Let's keep it open until you try the next version:)

**Comment by Evil95** [comment]
Okay dokay. :D

**Comment by maqjav** [comment]
I'm facing the same problem in my UK6200PLA, so I assume is the same problem.
Waiting for the patch with the fix.
Thanks for your work! ;)

**Comment by aidan-mundy** [comment]
Also no sound on my LG B2 OLED
ihsplay version 0.2.8
webos version 7.3.0
