### ISSUE TITLE
Video freeze on LG65C2PSC

### ISSUE THREAD

**Issue by sheaffe** [mariotaku/ihsplay#19]
## Issue Summary

The video stream freezes about 2 minutes after launching. Control input and audio continue working.
Until the freeze it works without issue.
Video will freeze after the same time regardless of desktop resolution or whether a game has been launched.

## Steps to Reproduce

Launch app. 
Wait 2 minutes. 
Video will freeze.

## Expected Behavior

Video should continue to stream along side audio.

## Basic Information

Model: OLED65C2PSC
Firmware: 03.30.16
webOS: 7.3.0

### IHSplay Information

Version: 0.2.3 (also occurred on 0.2.2)
Audio Module: ndl-webos5
Video Module: ndl-webos5
webOS Version: 7.3.0

### Computer Setup

Windows 10
i9-9900k
32GB RAM
RTX 2080ti

Monitor:
5120 x 1440 (32:9)
(have also attempted resolution of 16:9 2560x1440)

**Comment by mariotaku** [comment]
This sounds like a duplicate #15. Let's move on to the issue and have discussions.
