### ISSUE TITLE
[BUG] Crash when clicking start streaming button

### ISSUE THREAD

**Issue by Micadurp** [mariotaku/ihsplay#39]
## Issue Summary

Crashes when clicking start streaming button. 

## Steps to Reproduce

Have computer selected
Click start streaming button
Crash

## Expected Behavior

Dont crash

## Basic Information

found this in /var/log/reports/librdx/

RDXDErr2_ihsplay__Linux Crash: ihsplay crashes at location ?var?palm?jail?org.mariotaku.ihsplay?usr?lib?libkadaptor.so.1.0.0 (_Z11delete_flowP12_FlowManager+0x99) [0x93ef25ee]____ihsplay.6267.wl1mNt.gz
RDXDErr2_ihsplay__Linux Crash: ihsplay crashes at location ?var?palm?jail?org.mariotaku.ihsplay?usr?lib?libkadaptor.so.1.0.0 (_Z11delete_flowP12_FlowManager+0x99) [0x93f045ee]____ihsplay.5572.OxmstU.gz

### IHSplay Information

Version: 0.2.7
Audio Module: ndl-webos4
Video Module: ndl-webos4
System: webOS 4.9.0 (HE_DTV_W19P_AFADABAA)

### Computer Setup
Windows 10
NVIDIA GeForce RTX 3080
2560 x 1440 main monitor
I have multiple monitors

Steam just updated to its latest version with the new UI and stuff, no idea if that changes anything.

## Additional Context

No error, just crash and goes back to whatever input I have selected
Pc shows up on the options, just cant start streaming

**Comment by mariotaku** [comment]
I made a new release v0.2.8. It should fix the crashing issue for you.

**Comment by Micadurp** [comment]
Yup, worked great. Easily connects now.
But now the videostream freezes, like #15
