### ISSUE TITLE
Whats the tecnical difference between Moonlight and IHSPlay?

### ISSUE THREAD

**Issue by ebellumat** [mariotaku/ihsplay#47]
I see you maintain the both projects, Moonlight have more options but IHSPlay is more straightforward. What is better? Why exists two options to do the same thing?

**Comment by mariotaku** [comment]
I'd say nothing is better than moonlight at this moment. It's more mature (on both the client and server side), has better performance and has a huge community.
The only downside is that it's not as easy to setup as Steam Link, but I think that's totally comprehensible after the first setup.
