### ISSUE TITLE
Lots of issues

### ISSUE THREAD

**Issue by Leblayd** [mariotaku/ihsplay#8]
I'm fully aware this is very early, and thank you for the great work!
So, I wanted to test it, and here are my findings:

- I was able to install it without any issue.

- It can recognize my Steam Deck.
When connecting, I correctly had to enter a code. Cancelling worked, and entering the code worked, too.
But after the connection is established, the TV just shows a black screen. With no way to interact in any way. I had to restart the TV.

- It does not recognize my PC.
My phone and Deck have no issue connecting to it, though.
My PC and the TV are wired up, the other two wireless, so that _might_ be the reason behind the difference.

- I do not see a settings icon at all.
The question mark icon doesn't do anything.
The exit button works.

- When nothing is discovered, no button is selected by default (and only Up does anything: to select exit)
Cursor clicks work about 1/10 times, and the selection doesn't show up either

**Comment by mariotaku** [comment]
Hi! Thanks for your feedback.

> the TV just shows a black screen

1. Could you share the `audio_driver` and `video_driver` you've seen on the bottom right corner?
2. Does it have sound while streaming?
3. Did you try long-pressing the BACK button (or EXIT button)?

> It does not recognize my PC.
Does the TV and the PC in the same IP range?

> I do not see a settings icon at all. The question mark icon doesn't do anything.

Those are not implemented features. The question mark is planned to show some QR code to wiki of this repo.

> When nothing is discovered, no button is selected by default

I think a hint to trigger manual scan will come in handy.

**Comment by Leblayd** [comment]
1. `audio_driver: ndl-webos5`
`video_driver: ndl-webos5`
2. There is no sound, either.
3. The Exit button on the remote works. Brought up the bottom menu and managed to exit.
But I normally use my phone as a remote, and there, I don't have the Exit button, and long pressing doesn't work unfortunately.

Also, for the record:

- Model: `LG 50UK6300MLB`
- Software version: `05.50.10`
- WebOS version: `4.4.2-10 (goldilocks-gorongosa)`

> Does the TV and the PC in the same IP range?

Not sure if I understand right, but:
My router shows the local addresses, and it's set to assign 192.168.0.2 - 192.168.0.253.
So: my TV, PC, and everything else is in that range.

I now also tried it using Wireless (5GHz), and switching the Deck to 5Ghz (PC still just wired), but no change for either device.

> those are not implemented features

Ah gotcha. Just wanted to make sure that it isn't missing only for me, cause the screenshot in the readme showed a settings icon.
(Also, love the QR idea)

**Comment by Recvi** [comment]
First of all, very cool project!

My experience so far has been:

TV: LG OLED B1 55'
  Audio driver: ndl_webos5
  Video driver: ndl_webos5

With Steam Deck:
1. Initial pairing process is completed
2. Stream initiates correctly from TV (both audio and video are present)
3. After performing a couple of movements from steam deck or if I start a game, the frame gets frozen while audio still goes through. This behavior might be triggered with any overlay menu as opening the setting sidebar also freezes the frame.

With Laptop (windows 11):
Shows up on TV app correctly. Pairing is success. When the stream is initiated, the process is left hanging on loading phase. No sound or audio is coming through even after 5 minutes.

Lastly, I would like to support this project directly, I'm an senior dev, could you guide me on how I could best contribute to the project?

**Comment by mariotaku** [comment]
Hi everyone in this issue, thank you so much for trying ihsplay! I have released v0.2.0, and some of the issues should have been fixed.

---

@Recvi I really appreciate your interest of helping this project. If you have a rooted TV, you can find logs produced by ihsplay. If not, I'll implement some way to produce log too. Also we could speed up debugging process by making changes to the code together and build on your PC & install directly to test. 

If you are interested, feel free to open another issue, and let's have some detailed discussion there. (Also my discord is available and you can find me on discord in [openlgtv](https://discord.gg/nKQW6FPWeM))

**Comment by mariotaku** [comment]
I'll be closing this issue as most of them are fixed and some of them should be discussed in a separate issue. Thank you all for testing.
